### ISSUE TITLE
Consider replacing version command with built in --version

### ISSUE THREAD

**Issue by dturanski** [projectriff/riff-cli#10]
https://github.com/spf13/cobra#version-flag

**Comment by trisberg** [comment]
We already have a --version option for the function version - wouldn't that collide with this?

**Comment by dturanski** [comment]
Not necessarily.  Flags can be locally scoped or inherited by sub commands. This would be on the root command, 
`riff --version`.  This may not be propagated to sub commands `riff create --version` or `riff init --version` . The doc isn't clear, but hopefully it's a local flag.

**Comment by trisberg** [comment]
I still like `version` better since it is more consistent with kubectl and helm

```
$ kubectl --version
Error: unknown flag: --version
```

**Comment by dturanski** [comment]
Fine with me
