### ISSUE TITLE
Problems running init for Java function

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff-cli#21]
Running `riff init java --handler function.Dummy` results in:

```
function path /Users/trisberg/Test/riff/dummy/dummy.java does not exist
```

Supplying the `--artifact` option using `riff init java --handler function.Dummy -a dummy.jar` results in:

```
language java conflicts with artifact file extension dummy.jar
```

**Comment by trisberg** [comment]
I fixed the init issues but it seems that create doesn't work. The InitOptions doesn't seem to be populated with the chained commands and I get:

```
$ riff create java -f . -a target/upper-1.0.0.jar --handler functions.Upper
function path /Users/trisberg/Test/riff/upper/.jar does not exist
```

Any thoughts?  @dturanski

**Comment by dturanski** [comment]
@trisberg - Looking at it. artifact is not getting populated for some reason.
