### ISSUE TITLE
Improve error handling for logs

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff-cli#33]
Running `riff logs` depends on the transient nature of the pod running the function - we should have better error messages when the pod isn't in a state where the logs are accessible, right now you get stuff like:
```
$ riff logs -n square
Displaying logs for container sidecar of function square in namespace default

exit status 1: error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0

Error exit status 1 - Function square may not be currently active
```

would be nice to eliminate the jsonpath error

**Comment by ericbottard** [comment]
This issue was moved to projectriff/riff#314
