### ISSUE TITLE
Support custom templates for function resources and Dockerfile

### ISSUE THREAD

**Issue by dturanski** [projectriff/riff-cli#4]
There are hooks OOTB, e.g. `--config string   config file (default is $HOME/.riff.yaml)`  We should probably store path to templates, and potentially other things here

**Comment by dturanski** [comment]
Some initial stories:

* User wants to provide a custom Dockerfile for ,e.g., all <language> functions
* User wants to configure a function container spec for a all <language> functions
* User wants to provide custom Dockerfile for a specific function 
* User wants to configure a function container for a specific function

**Comment by ericbottard** [comment]
This issue was moved to projectriff/riff#316
