### ISSUE TITLE
install 'riff' binary instead of 'riff-cli'

### ISSUE THREAD

**Issue by jldec** [projectriff/riff-cli#43]
Is there a way to coerce go to use `riff` as the binary name?

```
~/go/src/github.com/projectriff/riff-cli (master)$ go install -v
github.com/projectriff/riff-cli
```

**Comment by trisberg** [comment]
This worked for me:

```
go install $GOPATH/src/github.com/projectriff/riff-cli/riff.go
```

**Comment by ericbottard** [comment]
I think the more idiomatic way is to have the `main` go package inside a `riff` directory, either in this repo or in the future monorepo.

Then
`go get github.com/projectriff/riff-cli/riff`

**Comment by glyn** [comment]
@ericbottard asked me to implement the idiomatic approach. Please see PR https://github.com/projectriff/riff-cli/pull/47.
