### ISSUE TITLE
Use http protocol for java

### ISSUE THREAD

**Issue by jldec** [projectriff/riff-cli#45]
In order to make the greeter sample work with the latest (http + grpc) java invoker, we should default to using the http protocol (riff init) and document that grpc only works for flux streams without correlated input and output events.

**Comment by trisberg** [comment]
I tried with the latest grpc PR and the --reply option seems to work with a simple example function using grpc as the protocol.

Not sure where we should document any protocol limitations, we don't really have any docs for the programming model ATM.

**Comment by jldec** [comment]
you're right - see https://github.com/projectriff/java-function-invoker/commit/60d675c48817cc75f17af76178afe588a5cd8b42

with https://github.com/projectriff/riff-cli/commit/f5b80a792fabfdf0466072ee54ea85194f9b494c the 0.0.4 CLI defaults to grpc for java.

closing.
