### ISSUE TITLE
Normalize FUNCTION_URI directory

### ISSUE THREAD

**Issue by scothis** [projectriff/riff-cli#50]
Each function invoker places the function to execute in a different location.

Java: `/functions`

Node: `/functions`

Python: `/`

Shell: `/`

We should always place functions into an empty directory since it's possible the function name could collide with a legitimate file path.

**Comment by markfisher** [comment]
maybe `/riff`?

**Comment by ericbottard** [comment]
This issue was moved to projectriff/riff#312
