### ISSUE TITLE
riff build command time out - Error context deadline exceeded

### ISSUE THREAD

**Issue by jldec** [projectriff/riff-cli#51]
I got this doing `riff create` for square with no cached images, on slowish (2Mb) wifi.

```
riff/samples/node/square (master)$ riff create --force
Initializing /Users/jleschner/riff/riff/samples/node/square/square-topics.yaml
Initializing /Users/jleschner/riff/riff/samples/node/square/square-function.yaml
Initializing /Users/jleschner/riff/riff/samples/node/square/Dockerfile
Initializing /Users/jleschner/riff/riff/samples/node/square/.dockerignore
Building image ...
signal: killed: 
Command timed out
Error context deadline exceeded
context deadline exceeded
```

If possible, I think it would be nice to display the progress ouput from the `docker build` and perhaps remove the timeout entirely (or offer a way to override it).

Running the `docker build` manually took a while but it worked.

**Comment by trisberg** [comment]
That looks like a docker timeout due to network issues, not sure there is much we can do in the CLI

**Comment by jldec** [comment]
aah, fair enough.
is there any way to relay the docker progress to stdout?

**Comment by trisberg** [comment]
not sure, will take a look to see what can be done

**Comment by jldec** [comment]
actually i don't believe this is a docker timeout

i keep getting the cli error, but when i invoke the `docker build... ` (using --dry-run to figure it out), the build succeeds.

**Comment by ericbottard** [comment]
This issue was moved to projectriff/riff#311
