### ISSUE TITLE
Set up public distribution of executables for Mac OS, Linux, Windows

### ISSUE THREAD

**Issue by dturanski** [projectriff/riff-cli#8]
Github, brew...

**Comment by jchesterpivotal** [comment]
Github is probably the easiest, insofar as we can use the existing [github release resource](https://github.com/concourse/github-release-resource).

For brew I think we'd be able to do something similar, but with another step or two in the pipeline.

**Comment by ericbottard** [comment]
This issue was moved to projectriff/riff#315
